<?php

return [
    'presets' => [
        'default' => [
            'editorType' => 'classic',
            'cloud' => [
                'editorVersion' => '47.3.0',
                'premium' => false,
                'translations' => ['en'],
            ],
            'config' => [
                'toolbar' => [
                    'items' => [
                        'undo',
                        'redo',
                        '|',
                        'heading',
                        '|',
                        'fontFamily',
                        'fontSize',
                        'fontColor',
                        'fontBackgroundColor',
                        'alignment',
                        '|',
                        'bold',
                        'italic',
                        'underline',
                        [
                            'label' => 'Text Style',
                            'items' => ['strikethrough', 'superscript', 'subscript'],
                        ],
                        '|',
                        'link',
                        'insertImage',
                        'insertTable',
                        'insertTableLayout',
                        'blockQuote',
                        'emoji',
                        'mediaEmbed',
                        '|',
                        'bulletedList',
                        'numberedList',
                        'todoList',
                        'outdent',
                        'indent',
                    ],
                ],
                'language' => 'en',
                'plugins' => [
                    'Alignment',
                    'AccessibilityHelp',
                    'Autoformat',
                    'AutoImage',
                    'Autosave',
                    'BlockQuote',
                    'Bold',
                    'CloudServices',
                    'Essentials',
                    'Emoji',
                    'Mention',
                    'Heading',
                    'FontFamily',
                    'FontSize',
                    'FontColor',
                    'FontBackgroundColor',
                    'ImageBlock',
                    'ImageCaption',
                    'ImageInline',
                    'ImageInsert',
                    'ImageInsertViaUrl',
                    'ImageResize',
                    'ImageStyle',
                    'ImageTextAlternative',
                    'ImageToolbar',
                    'ImageUpload',
                    'Indent',
                    'IndentBlock',
                    'Italic',
                    'Link',
                    'LinkImage',
                    'List',
                    'ListProperties',
                    'MediaEmbed',
                    'Paragraph',
                    'PasteFromOffice',
                    'PictureEditing',
                    'SelectAll',
                    'Table',
                    'TableLayout',
                    'TableCaption',
                    'TableCellProperties',
                    'TableColumnResize',
                    'TableProperties',
                    'TableToolbar',
                    'TextTransformation',
                    'TodoList',
                    'Underline',
                    'Strikethrough',
                    'Superscript',
                    'Subscript',
                    'Undo',
                    'Base64UploadAdapter',
                ],
                'table' => [
                    'contentToolbar' => [
                        'tableColumn',
                        'tableRow',
                        'mergeTableCells',
                        'tableProperties',
                        'tableCellProperties',
                        'toggleTableCaption',
                    ],
                ],
                'image' => [
                    'toolbar' => [
                        'imageTextAlternative',
                        'imageStyle',
                        'imageResize',
                        'imageInsertViaUrl',
                    ],
                ],
            ],
        ],
    ],
    'contexts' => [
        'default' => [
            'config' => [
                'plugins' => [],
            ],
        ],
    ],
];
