<?php

namespace Mati365\CKEditor5Symfony\Cloud;

use Mati365\CKEditor5Symfony\Cloud\CloudParser;

/**
 * Loader for Cloud configuration from `assets/vendor/ckeditor5-cloud/cloud.json`
 * which was generated by `ckeditor5:sitemap:install` command.
 */
final class CloudSingletonLoader
{
    private ?Cloud $cachedCloud = null;

    public function __construct(
        private readonly string $path
    ) {}

    /**
     * Loads and parses the cloud.json file into a Cloud instance.
     *
     * @return Cloud|null The parsed Cloud instance or null if file does not exist.
     */
    public function load(): ?Cloud
    {
        if ($this->cachedCloud !== null) {
            return $this->cachedCloud;
        }

        if (!file_exists($this->path)) {
            return null;
        }

        $json = file_get_contents($this->path);

        if ($json === false) {
            return null;
        }

        $data = json_decode($json, true);

        if (!is_array($data)) {
            return null;
        }

        $this->cachedCloud = CloudParser::parse($data);

        return $this->cachedCloud;
    }
}
